### ISSUE TITLE
Needs newer version of Java but I'm already on the latest public release of the JRE

### ISSUE THREAD

**Issue by Draugr-Knight** [Caltinor/Stackable#1]
I just spent an hour trying to make sure I don't have any older versions of Java lying around and that I was properly updated to the latest version, but I'm getting an error from this mod saying "Stackable has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0"

Full error log:
[crash-2023-12-01_07.04.40-fml.txt](https://github.com/Caltinor/Stackable/files/13527169/crash-2023-12-01_07.04.40-fml.txt)

**Comment by TressaDanvers** [comment]
This error only exists because the JAR posted to both modrinth and curseforge was compiled with the JDK-21, not the JDK-17 which it should have been. If you are on windows, you can download the project repo yourself (preferably using the git-for-windows cli utility, or the github desktop application), and then compile it yourself with the correct java version. Open a cli in the project directory; make sure your %JAVA_HOME% (or $JAVA_HOME in powershell) is pointed to a JDK-17 install, and run `gradlew jar`. If you are on linux I'm sure you can figure out how to do this on your own personal distro.

**Comment by Caltinor** [comment]
I rebuilt the JAR with the correct JDK and published the versions to CF and MR.  they should be available shortly.
